FROM kalilinux/kali-rolling

# update apt
RUN apt -y update

# essential tools
RUN apt install -y sudo
RUN apt install -y procps
RUN apt install -y net-tools
RUN apt install -y openvpn
RUN apt install -y iputils-ping
RUN apt install -y nmap
RUN apt install -y curl

# /etc/protocols and /etc/services
RUN apt install -y netbase

# other tools
RUN apt install -y ftp
RUN apt install -y smbclient
RUN apt install -y gobuster
RUN apt install -y nano

# kali tools
# RUN apt install -y kali-linux-headless

COPY code /code
COPY config /config
COPY startup.sh /startup.sh
